### ISSUE TITLE
Include SPDX license headers

### ISSUE THREAD

**Issue by tasn** [etesync/etebase-go#7]
Every file should have this at the top: https://github.com/etesync/ios/blob/master/src/AboutScreen.tsx#L1
(using the correct license identifier, which is BSD-3-Clause here I believe).

I know I've been a bit sloppy with doing it in other repos, but I'll add it all soon.

**Comment by tasn** [comment]
Also add an AUTHORS file and put yourself there, so that "Etebase Authors" actually refers to something meaningful. :P

**Comment by gchaincl** [comment]
that means:
```
// SPDX-FileCopyrightText: © 2019 EteSync Authors
// SPDX-License-Identifier: BSD-3-Clause
```
?
does this include `wait-for-it.sh` ?

**Comment by tasn** [comment]
Etebase Authors, not EteSync, but looks great otherwise.
Doesn't include wait-for-it as we don't own the copyright for that, I commented on the PR with an eaxmple for that script.
